FROM golang:1

ENV PROJECT=content-rw-neo4j
ENV REPO_PATH="github.com/Financial-Times/${PROJECT}"

ARG GITHUB_USERNAME
ARG GITHUB_TOKEN

COPY . $GOPATH/src/${REPO_PATH}

RUN echo "Fetching dependencies..." \
&& git config --global url."https://${GITHUB_USERNAME}:${GITHUB_TOKEN}@github.com".insteadOf "https://github.com" \
&& git clone https://github.com/vishnubob/wait-for-it.git \
&& cd wait-for-it \
&& mv ./wait-for-it.sh $GOPATH/src/${REPO_PATH}
&& go env -w GOPRIVATE=github.com/Financial-Times

WORKDIR $GOPATH/src/${REPO_PATH}

ENTRYPOINT ["./wait-for-it.sh", "neo4j:7474", "-t", "60", "--"]
