services:
  test-runner:
    build:
      context: .
      dockerfile: Dockerfile.tests
      args:
        GITHUB_USERNAME: "${GITHUB_USERNAME}"
        GITHUB_TOKEN: "${GITHUB_TOKEN}"
    container_name: test-runner
    environment:
      - NEO4J_TEST_URL=bolt://neo4j:7687
      - CGO_ENABLED=1
      - OPA_URL=http://opa:8181
    command: ["go", "test", "-mod=readonly", "-v", "-race", "-tags=integration", "./..."]
    depends_on:
      - neo4j
      - opa
  neo4j:
    image: neo4j:4.4-enterprise
    environment:
      NEO4J_AUTH: none
      NEO4J_ACCEPT_LICENSE_AGREEMENT: "yes"
    ports:
      - "7474:7474"
      - "7687:7687"
  opa:
    image: openpolicyagent/opa:0.62.1
    ports:
      - "8181:8181"
    command:
      - "run"
      - "--server"
      - "--log-format=json"
      - "--set=decision_logs.console=true"
