version: '3'
services:
  test-runner:
    build:
      context: .
      dockerfile: Dockerfile.tests
      args:
        GITHUB_USERNAME: "${GITHUB_USERNAME}"
        GITHUB_TOKEN: "${GITHUB_TOKEN}"
    container_name: test-runner
    environment:
      - NEO4J_TEST_URL=bolt://neo4j:7687
      - CGO_ENABLED=1
    command: ["go", "test", "-mod=readonly", "-v", "-race", "-tags=integration", "./..."]
    depends_on:
      - neo4j
  neo4j:
    image: neo4j:3.5-enterprise
    environment:
      NEO4J_AUTH: none
      NEO4J_ACCEPT_LICENSE_AGREEMENT: "yes"
    ports:
      - "7474:7474"
      - "7687:7687"
