version: 2.1

orbs:
  ft-golang-ci: financial-times/golang-ci@2

executors:
  default-with-neo4j-and-opa:
    docker:
      - image: golang:1
        environment:
          GOPATH: /go
          NEO4J_TEST_URL: "bolt://localhost:7687"
          OPA_URL: "http://localhost:8181"
      - image: neo4j:4.3.10-enterprise
        environment:
          NEO4J_AUTH: none
          NEO4J_HEAP_MEMORY: 256
          NEO4J_CACHE_MEMORY: 256M
          NEO4J_ACCEPT_LICENSE_AGREEMENT: "yes"
      - image: openpolicyagent/opa:0.62.1
        command: [ "run", "--server", "--addr=0.0.0.0:8181", "--log-level=error", "--log-format=json"]

jobs:
  dredd:
    executor: default-with-neo4j-and-opa
    working_directory: /go/src/github.com/Financial-Times/content-rw-neo4j
    steps:
    - checkout
    - run:
        name: Unset ssh instead of https
        command: git config --global --unset url."ssh://git@github.com".insteadOf
    - run:
        name: Set GITHUB_USERNAME and GITHUB_TOKEN
        command: git config --global url."https://${GITHUB_USERNAME}:${GITHUB_TOKEN}@github.com".insteadOf "https://github.com"
    - run:
        name: Go Build
        command: go build -mod=readonly -v
    - run:
        name: Download dredd
        command: |
            curl -sL https://deb.nodesource.com/setup_14.x | bash -
            DEBIAN_FRONTEND=noninteractive apt-get install -y nodejs=14.\*
            npm install -g --unsafe-perm --loglevel warn --user 0 --no-progress dredd@8.0.0
            rm -rf /var/lib/apt/lists/*
    - run:
        name: Add a dummy OPA policy.
        command: |
          curl --location --request PUT 'localhost:8181/v1/policies/c1d20fbc-e9bc-44fb-8b88-0e01d6b13225' \
          --header 'Content-Type: text/plain' \
          --data 'package content_rw_neo4j.special_content default is_special_content := false'
    - run:
        name: Dredd API Testing
        command: dredd

workflows:
  tests_and_docker:
    jobs:
      - dredd:
          context: cm-team-github
      - ft-golang-ci/build-and-test:
          name: build-and-test-project
          executor-name:
            name: default-with-neo4j-and-opa
          context: cm-team-github
      - ft-golang-ci/docker-build:
          name: build-docker-image
          requires:
            - build-and-test-project
          context: cm-team-github
