name    'ft-content_rw_neo4j'
version '0.0.17'
source 'UNKNOWN'
author 'ft'
license 'Apache License, Version 2.0'
summary 'UNKNOWN'
description 'UNKNOWN'
project_page 'UNKNOWN'

## Add dependencies, if any:
dependency 'ft/common_pp_up', '1.0.x'
dependency 'ft/satellitesubscribe', '0.0.x'
dependency 'ft/go_service_profile', '>= 0.0.0'
