# Default values for content-rw-neo4j.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
service:
  name: "" # The name of the service, should be defined in the specific app-configs folder.
  hasHealthcheck: "true"
replicaCount: 2
image:
  repository: coco/content-rw-neo4j
  pullPolicy: IfNotPresent
openPolicyAgentSidecar:
  name: open-policy-agent
  repository: openpolicyagent/opa
  tag: 0.61.0
  pullPolicy: IfNotPresent
serviceAccount: eksctl-content-rw-neo4j-serviceaccount
resources:
  requests:
    memory: 40Mi
  limits:
    memory: 256Mi
env:
  opaUrl: "http://localhost:8181"
  opaSpecialContentPolicyPath: "content_rw_neo4j/special_content"